# Generated by Django 5.2.17 on 2026-09-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_latitude_profile_location_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='board_background',
            field=models.CharField(default='transparent', max_length=20),
        ),
    ]
