# Generated by Django 5.2.17 on 2026-09-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_board_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme_accent_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme_background',
            field=models.ImageField(blank=True, upload_to='theme_backgrounds/'),
        ),
    ]
