# Generated by Django 5.2.17 on 2026-09-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_theme_accent_color_profile_theme_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme_effect',
            field=models.CharField(blank=True, choices=[('', 'None'), ('winter', 'Winter'), ('summer', 'Summer'), ('rain', 'Rain'), ('blossom', 'Cherry Blossom')], max_length=10),
        ),
    ]
