# Generated by Django 5.2.17 on 2026-09-22 08:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=10)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='vision_board/')),
                ('color', models.CharField(choices=[('cream', 'Cream'), ('accent', 'Accent'), ('accent-soft', 'Accent soft'), ('slate', 'Slate')], default='cream', max_length=20)),
                ('done', models.BooleanField(default=False)),
                ('x', models.FloatField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('y', models.FloatField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rotation', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-25), django.core.validators.MaxValueValidator(25)])),
                ('z_index', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_pins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['z_index', 'created_at'],
            },
        ),
    ]
