# Generated by Django 5.2.17 on 2026-09-22, hand-edited to preserve data:
# adds `visibility` while `is_public` still exists, copies True -> 'public',
# then drops `is_public` — instead of the auto-generated remove+add that
# would silently lose which entries were public.

from django.db import migrations, models


def copy_is_public_to_visibility(apps, schema_editor):
    Day = apps.get_model("days", "Day")
    Day.objects.filter(is_public=True).update(visibility="public")


def copy_visibility_to_is_public(apps, schema_editor):
    Day = apps.get_model("days", "Day")
    Day.objects.filter(visibility="public").update(is_public=True)


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0002_alter_day_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('friends', 'Friends'), ('public', 'Public')], default='private', max_length=10),
        ),
        migrations.RunPython(copy_is_public_to_visibility, copy_visibility_to_is_public),
        migrations.RemoveField(
            model_name='day',
            name='is_public',
        ),
    ]
