# Generated by Django 5.2.17 on 2026-09-30 16:13

import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(storage=music.models.audio_storage, upload_to='songs/'),
        ),
    ]
